### ISSUE TITLE
add tests that round-trip across vfio-user protocol

### ISSUE THREAD

**Issue by jlevon** [nutanix/libvfio-user#101]
Need to figure out if/how we can adapt the sample client/server code to be the basis of a test suite and start covering some of the basic interactions automatically.

**Comment by tmakatos** [comment]
FYI I've tentatively included the cmocka unit test framework in #119.

**Comment by tmakatos** [comment]
In https://github.com/nutanix/muser/pull/129, because functions within the same file can't be mocked using the `-Wl,--wrap` trick I have to essentially redefine the function with it's wrapped version within the source file. While this change is minimal, we do have to change the source to accomodate unit testing. We need to define whether the unit of a unit test is a function or a whole file. If it's the latter then we won't have to do such tricks but we limit which functions we can test. @jlevon @swapnili thoughts?

**Comment by jlevon** [comment]
Updating this ticket a little bit. We have a reasonable level of coverage in terms of unit tests plus some other parts. #238 will add some basic vfio-user protocol usage. But it would be nice to have this expanded for fuller coverage of the protocol.

**Comment by jlevon** [comment]
I'm marking this is basically fixed now we have the Python framework.
