### ISSUE TITLE
optimize VirtIO doorbell kicks

### ISSUE THREAD

**Issue by tmakatos** [nutanix/libvfio-user#18]
VirtIO doorbell kicks don’t carry any information, it’s just a memory access. Therefore we don’t have  to fully emulate the write (which means VM->KVM->QEMU->VFIO->muser.ko->libmuser and back). Instead, we can setup an ioeventfd notifier so the kick is VM->KVM and back. In KVM, all that happens is an eventfd write which libmuser can catch via epoll or similar (or even spin on it if it wants). But currently we have no mechanism to implement that notifier, so emulating a VirtIO device on MUSER would be much slower than QEMU or vhost.

**Comment by stefanha** [comment]
It would be nice to expose the full ioeventfd API (which allows matching on specific data, setting the size of the memory access, etc) in libmuser.  A new VFIO ioctl API could be added so the VMM can receive the eventfd together with the metadata and install it in kvm.ko or emulate it some other way.

By the way, Elena, JJ, and Jag from Oracle have discussed the idea of a more powerful ioeventfd that does carry information so that even synchronous reads can be supported.  I'm not aware code implementing this idea yet but it would allow the device emulation program to be notified directly by kvm.ko instead of a longer path through muser.ko.

**Comment by tmakatos** [comment]
For completeness here's the discusison: https://www.spinics.net/lists/kvm/msg208139.html

**Comment by jlevon** [comment]
Being dealt with via #231
