### ISSUE TITLE
Have a way to let device(user) know dma_regions are not mmap'ed()

### ISSUE THREAD

**Issue by swapnili** [nutanix/libvfio-user#203]
If vfio-user-client do not provide fd to map dma_regions (VFIO_USER_DMA_MAP) then device can use VFIO_USER_DMA_READ/VFIO_USER_DMA_WRITE to access the regions.
We will need a way that device implementation can query to figure this out.

**Comment by tmakatos** [comment]
@swapnili in https://github.com/nutanix/libvfio-user/pull/211 we now fail mapping a DMA segment, so the user is made aware that there's no file descriptor. I understand that this doesn't fix the original problem (having a way for the user to query whether or not the DMA region can be memory mapped), however this check is necessary anyway. Regarding the original problem, I'm not sure how easy it is to fix since a segment can span multiple regions and one region is mapped while the other isn't, so the user will have to figure out which DMA regions they'll need to use in the first place, which this is exactly what `dma_map_sg` does anyway.

**Comment by swapnili** [comment]
How about adding mappable={true|false} into dma_sg_t?
So based on this field user can do messaged DMA read/write if region is not mapped.

**Comment by tmakatos** [comment]
> How about adding mappable={true|false} into dma_sg_t?
> So based on this field user can do messaged DMA read/write if region is not mapped.

That's a good idea!
