### ISSUE TITLE
dirty page logging: race condition betweeen starting logging dirty pages and mapping segment

### ISSUE THREAD

**Issue by tmakatos** [nutanix/libvfio-user#540]
@jlevon pointed out the following problem: if a DMA segment is already mapped (e.g. SPDK has mapped the admin queue) and dirty page logging is started afterwards, we'll miss logging the relevant pages. Even worse, if https://github.com/nutanix/libvfio-user/issues/526 turns out to be true (we must reset the bitmap each time VFIO_USER_DIRTY_PAGES is executed), then we'll again miss logging the relevant pages.

Possible solutions:

1. Introduce a function that the user calls to mark page dirty. This should solve the problem (might have to introduce locks) but makes it harder to use for the client.
2. Keep track of currently mapped segments and set the relevant bits when dirty page logging is started or when the bitmap is requested. This is easier for the user but we might end up dirtying more pages than necessary.

The above solutions are not mutually exclusive: the client can specify whether dirty page tracking must be implicit or explicit.

**Comment by tmakatos** [comment]
@jlevon an alternative to keeping track of currently mapped segments it to used a currently mapped bitmap: each bit tells whether or not an area of a DMA region is currently mapped. This "area" doesn't necessarily have to be a page, it can operate on larger granularity, e.g. 2 MB regions. This way the memory footprint will be low at the cost of reporting clean pages as dirty. This approach trades memory footprint for speed.

**Comment by jlevon** [comment]
I think it's worthwhile doing a write-up - a markdown draft in docs/ would do - that describes what we want the whole thing to look like.

The problem with a "mapped" bitmap (actually, what we really want is an "unmapped" bitmap), is it can't account for multiple sg's covering the same pages.

Without mapping, only way to write to guest memory is vfu_dma_write(). We don't need to worry about that (either dirty in libvfio-user, or let the client handle it - should add that to the spec).

So, first thing I think we need is to move the dirtying from vfu_addr_to_sg() to vfu_map_sg(). This would likely include moving 'prot' too - we can check prot instead directly in vfu_dma_read/write() for the non-mapped case.

Then, in vfu_map_sg, we take "prot" to check, as well as a flag that means "we'll explicitly mark". Add a vfu_mark_dirty API of some sort. I think this is relatively trivial - such ranges explicitly dirty bits and otherwise don't need to be taken into account - so won't comment further.

So, how do we clear bits after copying out the dirty bitmap at DIRTY_PAGES time? The stupidest implementation is that at map time, we keep a list of every SG, then to see if we can clear a page, we walk the full list: if we don't find it, it's fine to clear, as SPDK cannot write to the page.

This is obviously horrible in terms of performance, so we would want a better data structure...

**Comment by jlevon** [comment]
(As an example of "better": add each map/unmap to a log (O(1) append), then process/compact that log at DIRTY_PAGES time.)

**Comment by tmakatos** [comment]
> The problem with a "mapped" bitmap (actually, what we really want is an "unmapped" bitmap), is it can't account for multiple sg's covering the same pages.

Good point.

> So, first thing I think we need is to move the dirtying from vfu_addr_to_sg() to vfu_map_sg(). This would likely include moving 'prot' too - we can check prot instead directly in vfu_dma_read/write() for the non-mapped case.

Yes, `vfu_addr_to_sg()` is not the right place to do all this.

> So, how do we clear bits after copying out the dirty bitmap at DIRTY_PAGES time? The stupidest implementation is that at map time, we keep a list of every SG, then to see if we can clear a page, we walk the full list: if we don't find it, it's fine to clear, as SPDK cannot write to the page.
> 
> This is obviously horrible in terms of performance, so we would want a better data structure...

We can keep a list of mapped segments and at DIRTY_PAGES time we clear the bitmap and then walk the list and turn on the relevant bits. I wouldn't expect this list to grow too big, for SPDK it will only be the queues and in-flight I/Os. Also, the user maintains `dma_sg_t` so we won't even have to dynamically allocate memory. The only cost is adding a segment to the list which is fast.

**Comment by jlevon** [comment]
> clear the bitmap and then walk the list and turn on the relevant bits

Need to be careful with races I think.

> walk the list

I don't know if you meant this loosely, but a growable array would be way better.

I thought yesterday that we needed to still track an sg after vfu_unmap_sg(), but I think I was wrong.
If we get a DIRTY_PAGES *before* unmap, we keep the dirty bit set. If it comes in *after* unmap, then the bit will still be set (and copied), and we are then OK to clear.

**Comment by tmakatos** [comment]
> > clear the bitmap and then walk the list and turn on the relevant bits
> 
> Need to be careful with races I think.

Oh yes, the DMA controller in general is not multi-threaded.

> > walk the list
> 
> I don't know if you meant this loosely, but a growable array would be way better.

No, I didn't mean it loosely. Why would a growable array be better? Using a list we don't have to allocate memory. Is it because iteration would be faster?

> I thought yesterday that we needed to still track an sg after vfu_unmap_sg(), but I think I was wrong.
If we get a DIRTY_PAGES before unmap, we keep the dirty bit set. If it comes in after unmap, then the bit will still be set (and copied), and we are then OK to clear.

Correct.

**Comment by jlevon** [comment]
linked lists are pretty much the worst data structure for modern computer systems. If we're expecting a  small-ish maximum of mappings, then a growable array is way better for cache locaility etc. And the allocation is amortized if you leave it grown.
