### ISSUE TITLE
make DMA map/unmap optionally asynchronous

### ISSUE THREAD

**Issue by tmakatos** [nutanix/libvfio-user#605]
Some devices (e.g. NVMf/vfio-user in SPDK) need the DMA map/unmap callbacks to be asynchronous: the device callback can return but it doesn't mean that the DMA unmap operation can continue (libvfio-user must not call `munmap`, e.g. there can be pending I/Os). We can solve this problem the same way we plan to solve making the migration device state transition callback asynchronous (https://github.com/nutanix/libvfio-user/issues/296#issuecomment-916812012).

Another way to solve this (as suggested by @changpe1) is to have a reference counter and unmap it when the last reference is dropped, however there can be problems with thread safety there. @jlevon thoughts?

**Comment by jlevon** [comment]
cf #594 

We can't do a reference count - what happens if a remap comes in? What happens if we send a DMA_WRITE across the socket after we responded to the unmap?

The only reasonable approach we've found is the first one: everything at the vfio-user socket level is blocked until SPDK tells us it's done with the unmap.

**Comment by tmakatos** [comment]
cf #296
